/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const classNames: typeof import('classnames')['classNames'];
  const createRef: typeof import('react')['createRef'];
  const formatNumber: typeof import('./utils/formatNumber')['default'];
  const forwardRef: typeof import('react')['forwardRef'];
  const lazy: typeof import('react')['lazy'];
  const memo: typeof import('react')['memo'];
  const providerHelper: typeof import('./utils/providerHelper')['default'];
  const regex: typeof import('./utils/regex')['default'];
  const required: typeof import('./utils/regex')['required'];
  const settingsService: typeof import('./services/settingsService')['default'];
  const startTransition: typeof import('react')['startTransition'];
  const useCallback: typeof import('react')['useCallback'];
  const useContext: typeof import('react')['useContext'];
  const useDebugValue: typeof import('react')['useDebugValue'];
  const useDeferredValue: typeof import('react')['useDeferredValue'];
  const useEffect: typeof import('react')['useEffect'];
  const useId: typeof import('react')['useId'];
  const useImperativeHandle: typeof import('react')['useImperativeHandle'];
  const useInsertionEffect: typeof import('react')['useInsertionEffect'];
  const useLayoutEffect: typeof import('react')['useLayoutEffect'];
  const useMemo: typeof import('react')['useMemo'];
  const useReducer: typeof import('react')['useReducer'];
  const useRef: typeof import('react')['useRef'];
  const useRouter: typeof import('next/router')['useRouter'];
  const useState: typeof import('react')['useState'];
  const useSyncExternalStore: typeof import('react')['useSyncExternalStore'];
  const useTransition: typeof import('react')['useTransition'];
}
// for type re-export
declare global {
  // @ts-ignore
  export type { ChangeEvent } from 'react';
  // @ts-ignore
  export type { NextPage } from 'next';
}
