import Head from 'next/head';

import OnboardingWizardLayout, {
  LeftSideLayout,
  RightSideLayout
} from '../../components/onboarding-wizard/OnboardingWizardLayout';
import LabelledInput from '../../components/onboarding-wizard/LabelledInput';
import CredentialsButton from '../../components/onboarding-wizard/CredentialsButton';

export default function AzureCredentials() {
  const handleNext = () => { };

  return (
    <div>
      <Head>
        <title>Setup Azure - Komiser</title>
        <meta name="description" content="Setup Azure - Komiser" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <OnboardingWizardLayout>
        <LeftSideLayout
          title="Configure your Microsoft Azure account"
          progressBarWidth="45%"
        >
          <div className="leading-6 text-gray-900/60">
            <div className="font-normal">
              Microsoft Azure is Microsoft&apos;s public cloud computing
              platform. It provides a broad range of cloud services, including
              compute, analytics, storage and networking. Users can pick and
              choose from these services to develop and scale new applications
              or run existing applications in the public cloud.
            </div>
            <div>
              Read our guide on{' '}
              <a
                target="_blank"
                href="https://docs.komiser.io/docs/cloud-providers/aws"
                className="text-komiser-600"
                rel="noreferrer"
              >
                adding an Azure account to Komiser.
              </a>
            </div>
          </div>

          <div className="flex flex-col space-y-4 py-10">
            <LabelledInput
              label="Account name"
              placeholder="my-azure-account"
            />

            <div className="flex flex-col space-y-[0.2] rounded-md bg-komiser-100 p-5">
              <LabelledInput label="Source" placeholder="" />
              <LabelledInput
                label="Tenant ID"
                subLabel="The ID of the AAD directory in which you created the application"
                placeholder="00000-00000-00000-00000"
              />
              <LabelledInput
                label="Client ID"
                subLabel="The secret access key is generated by AWS when an access key is created"
                placeholder="aSbG%hF7kL9p#2jN5mH8qR3tV6wZ"
              />
              <LabelledInput
                label="Client secret"
                subLabel="You can find it as the authentication key string"
                placeholder="9e5b97c6-16a1-4f5d-a3a7-62c4b3b0d8c7"
              />
              <LabelledInput
                label="Subscription ID"
                subLabel="The subscription ID is a GUID that uniquely identifies your subscription to use Azure services"
                placeholder="abcdef12-3456-7890-1234-567890abcdef"
              />
            </div>
          </div>

          <CredentialsButton handleNext={handleNext} />
        </LeftSideLayout>

        <RightSideLayout>
          <div className="relative">
            <p>Azure Video Here</p>
          </div>
        </RightSideLayout>
      </OnboardingWizardLayout>
    </div>
  );
}
