// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"

	autoscaling "github.com/aws/aws-sdk-go-v2/service/autoscaling"

	mock "github.com/stretchr/testify/mock"
)

// AutoScalingGroupClient is an autogenerated mock type for the AutoScalingGroupClient type
type AutoScalingGroupClient struct {
	mock.Mock
}

// DescribeAutoScalingGroups provides a mock function with given fields: ctx, params, optFns
func (_m *AutoScalingGroupClient) DescribeAutoScalingGroups(ctx context.Context, params *autoscaling.DescribeAutoScalingGroupsInput, optFns ...func(*autoscaling.Options)) (*autoscaling.DescribeAutoScalingGroupsOutput, error) {
	_va := make([]interface{}, len(optFns))
	for _i := range optFns {
		_va[_i] = optFns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *autoscaling.DescribeAutoScalingGroupsOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *autoscaling.DescribeAutoScalingGroupsInput, ...func(*autoscaling.Options)) (*autoscaling.DescribeAutoScalingGroupsOutput, error)); ok {
		return rf(ctx, params, optFns...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *autoscaling.DescribeAutoScalingGroupsInput, ...func(*autoscaling.Options)) *autoscaling.DescribeAutoScalingGroupsOutput); ok {
		r0 = rf(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*autoscaling.DescribeAutoScalingGroupsOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *autoscaling.DescribeAutoScalingGroupsInput, ...func(*autoscaling.Options)) error); ok {
		r1 = rf(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewAutoScalingGroupClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewAutoScalingGroupClient creates a new instance of AutoScalingGroupClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAutoScalingGroupClient(t mockConstructorTestingTNewAutoScalingGroupClient) *AutoScalingGroupClient {
	mock := &AutoScalingGroupClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
